<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-N83H8S6" name="com.jbk.OfflineWebsite.LoginPage" tests="7" failures="1" timestamp="8 Sep 2021 06:41:31 GMT" time="74.110" errors="0">
  <testcase name="verifyLogo" time="8.879" classname="com.jbk.OfflineWebsite.LoginPage"/>
  <testcase name="verifyTitle" time="15.603" classname="com.jbk.OfflineWebsite.LoginPage"/>
  <testcase name="CheckWithInvalidPassword" time="6.623" classname="com.jbk.OfflineWebsite.LoginPage">
    <failure type="java.lang.AssertionError" message="expected [Please enter password 123456] but found [Please enter email]">
      <![CDATA[java.lang.AssertionError: expected [Please enter password 123456] but found [Please enter email]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.jbk.OfflineWebsite.LoginPage.CheckWithInvalidPassword(LoginPage.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:823)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:778)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1225)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1150)
	at org.testng.TestNG.runSuites(TestNG.java:1075)
	at org.testng.TestNG.run(TestNG.java:1047)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
    </failure>
  </testcase> <!-- CheckWithInvalidPassword -->
  <testcase name="RegNewUser" time="13.669" classname="com.jbk.OfflineWebsite.LoginPage"/>
  <testcase name="CheckwWithValidCreds" time="11.011" classname="com.jbk.OfflineWebsite.LoginPage"/>
  <testcase name="verifyText1" time="12.813" classname="com.jbk.OfflineWebsite.LoginPage"/>
  <testcase name="CheckWithInvalidUsername" time="5.512" classname="com.jbk.OfflineWebsite.LoginPage"/>
</testsuite> <!-- com.jbk.OfflineWebsite.LoginPage -->
